"""empty message

Revision ID: 58db9987410e
Revises: None
Create Date: 2015-04-15 00:32:40.321993

"""

# revision identifiers, used by Alembic.
revision = '58db9987410e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
